[assembly: System.Reflection.AssemblyTitle("ADOUtils")]
[assembly: System.Reflection.AssemblyProduct("ADOUtils")]
[assembly: System.Reflection.AssemblyDescription("ADO.NET utilities")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Gian Marco Gherardi 2012")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCompany("Gian Marco Gherardi")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyVersion("0.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.1.0.0")]